DROP TABLE IF EXISTS tbl_approach CASCADE;
DROP TABLE IF EXISTS tbl_exercise CASCADE;
DROP TABLE IF EXISTS tbl_muscles CASCADE;
DROP TABLE IF EXISTS tbl_workout CASCADE;
DROP SEQUENCE IF EXISTS entity_id_seq;

create sequence entity_id_seq start with 1 increment by 1;

create table tbl_approach (
id INTEGER GENERATED BY DEFAULT AS SEQUENCE entity_id_seq PRIMARY KEY,
distance float,
repeats integer,
time time,
weight float,
exercise_id integer not null
);

create table tbl_exercise (
id INTEGER GENERATED BY DEFAULT AS SEQUENCE entity_id_seq PRIMARY KEY,
comment varchar(255),
distanceMeasure boolean,
repeatMeasure boolean,
timeMeasure boolean,
weightMeasure boolean,
complexity varchar(255) not null,
description varchar(255),
exercise_name varchar(255) not null,
type varchar(255) not null,
workout_id integer not null
);

create table tbl_muscles (
exercise_id integer not null,
goal_of_working_muscle varchar(255),
muscle_name varchar(50) not null
);

create table tbl_workout (
id INTEGER GENERATED BY DEFAULT AS SEQUENCE entity_id_seq PRIMARY KEY,
name varchar(255) not null,
endWorkout timestamp,
startWorkout timestamp
);

alter table tbl_muscles add constraint working_muscle_unique_exercise_id_idx unique (exercise_id, muscle_name);
alter table tbl_approach add constraint FK1n9c2cy2r39rn0wh5ro3rl820 foreign key (exercise_id) references tbl_exercise;
alter table tbl_exercise add constraint FKgh5wmo31kl2famkl6iohd7a14 foreign key (workout_id) references tbl_workout;
alter table tbl_muscles add constraint FKfv725yd3ymnhmujh42ujj5aqi foreign key (exercise_id) references tbl_exercise;
